services:
  # Development environment
  bithub-web-dev:
    container_name: bithub-web-dev
    build:
      context: ../..
      dockerfile: apps/web/Dockerfile.dev
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    networks:
      - app-net
    command: npm run dev -- --host

  # Production environment
  bithub-web-prod:
    container_name: bithub-web-prod
    # image: lcaohoanq/bithub-web:serve-nginx
    image: lcaohoanq/bithub-web:enterprise
    build:
      context: ../..
      dockerfile: apps/web/Dockerfile.prod
    ports:
      - "5174:5173"
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=/api
      - VITE_PRODUCT_API_BASE_URL=https://bithub-presentation.taskgenix.website/api
    networks:
      - app-net

networks:
  app-net:
    external: true
