---
services:
  bitlearning-web-deploy-prod:
    image: hoangclw/bitlearning-web:prod-latest
    expose:
      - "5173"
    mem_limit: 1024m
    cpus: 1.0
    restart: unless-stopped
    networks:
      - app-network

  bitlearning-admin-deploy-prod:
    image: hoangclw/bitlearning-admin:prod-latest
    expose:
      - "8386"
    mem_limit: 1024m
    cpus: 1.0
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    external: true
    name: bitlearning-network
