/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CorporateTrainingRouteImport } from './routes/corporate-training'
import { Route as CoursesIdRouteImport } from './routes/courses/$id'
import { Route as CoursesBackendDevelopmentRouteImport } from './routes/courses/backend-development'
import { Route as CoursesDataScienceRouteImport } from './routes/courses/data-science'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as CoursesMobileDevelopmentRouteImport } from './routes/courses/mobile-development'
import { Route as CoursesWebDevelopmentRouteImport } from './routes/courses/web-development'
import { Route as CustomTemplateRouteImport } from './routes/custom-template'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatricesIdEditRouteImport } from './routes/matrices/$id.edit'
import { Route as MatricesIdGenerateRouteImport } from './routes/matrices/$id.generate'
import { Route as MatricesCreateRouteImport } from './routes/matrices/create'
import { Route as MatricesImportRouteImport } from './routes/matrices/import'
import { Route as MatricesIndexRouteImport } from './routes/matrices/index'
import { Route as MentorshipRouteImport } from './routes/mentorship'
import { Route as NewsIdRouteImport } from './routes/news/$id'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as OfflineCourseRouteImport } from './routes/offline-course'
import { Route as PresentationsIdRouteImport } from './routes/presentations/$id'
import { Route as PresentationsIdOverviewRouteImport } from './routes/presentations/$id/overview'
import { Route as PresentationsIdPresenterRouteImport } from './routes/presentations/$id/presenter'
import { Route as PresentationsIdViewRouteImport } from './routes/presentations/$id/view'
import { Route as PresentationsIndexRouteImport } from './routes/presentations/index'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TemplatesIdRouteImport } from './routes/templates/$id'
import { Route as TemplatesDashboardRouteImport } from './routes/templates/dashboard'
import { Route as TemplatesIndexRouteImport } from './routes/templates/index'
import { Route as TemplatesSlidevIdEditRouteImport } from './routes/templates/slidev/$id/edit'
import { Route as TemplatesSlidevCreateRouteImport } from './routes/templates/slidev/create'
import { Route as TemplatesSlidevIndexRouteImport } from './routes/templates/slidev/index'
import { Route as TemplatesTemplatePreviewRouteImport } from './routes/templates/template-preview'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as UserProfileRouteImport } from './routes/user-profile'
import { Route as WebDesignRouteImport } from './routes/web-design'

const WebDesignRoute = WebDesignRouteImport.update({
    id: '/web-design',
    path: '/web-design',
    getParentRoute: () => rootRouteImport,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
    id: '/user-profile',
    path: '/user-profile',
    getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
    id: '/upload',
    path: '/upload',
    getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
    id: '/terms',
    path: '/terms',
    getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
    id: '/signup',
    path: '/signup',
    getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
    id: '/signin',
    path: '/signin',
    getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
    id: '/reset-password',
    path: '/reset-password',
    getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
    id: '/privacy',
    path: '/privacy',
    getParentRoute: () => rootRouteImport,
} as any)
const OfflineCourseRoute = OfflineCourseRouteImport.update({
    id: '/offline-course',
    path: '/offline-course',
    getParentRoute: () => rootRouteImport,
} as any)
const MentorshipRoute = MentorshipRouteImport.update({
    id: '/mentorship',
    path: '/mentorship',
    getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
    id: '/demo',
    path: '/demo',
    getParentRoute: () => rootRouteImport,
} as any)
const CustomTemplateRoute = CustomTemplateRouteImport.update({
    id: '/custom-template',
    path: '/custom-template',
    getParentRoute: () => rootRouteImport,
} as any)
const CorporateTrainingRoute = CorporateTrainingRouteImport.update({
    id: '/corporate-training',
    path: '/corporate-training',
    getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
    id: '/consultation',
    path: '/consultation',
    getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
    id: '/chat',
    path: '/chat',
    getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => rootRouteImport,
} as any)
const PresentationsIndexRoute = PresentationsIndexRouteImport.update({
    id: '/presentations/',
    path: '/presentations/',
    getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
    id: '/news/',
    path: '/news/',
    getParentRoute: () => rootRouteImport,
} as any)
const MatricesIndexRoute = MatricesIndexRouteImport.update({
    id: '/matrices/',
    path: '/matrices/',
    getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => rootRouteImport,
} as any)
const TemplatesTemplatePreviewRoute = TemplatesTemplatePreviewRouteImport.update({
    id: '/templates/template-preview',
    path: '/templates/template-preview',
    getParentRoute: () => rootRouteImport,
} as any)
const TemplatesDashboardRoute = TemplatesDashboardRouteImport.update({
    id: '/templates/dashboard',
    path: '/templates/dashboard',
    getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIdRoute = TemplatesIdRouteImport.update({
    id: '/templates/$id',
    path: '/templates/$id',
    getParentRoute: () => rootRouteImport,
} as any)
const PresentationsIdRoute = PresentationsIdRouteImport.update({
    id: '/presentations/$id',
    path: '/presentations/$id',
    getParentRoute: () => rootRouteImport,
} as any)
const NewsIdRoute = NewsIdRouteImport.update({
    id: '/news/$id',
    path: '/news/$id',
    getParentRoute: () => rootRouteImport,
} as any)
const MatricesImportRoute = MatricesImportRouteImport.update({
    id: '/matrices/import',
    path: '/matrices/import',
    getParentRoute: () => rootRouteImport,
} as any)
const MatricesCreateRoute = MatricesCreateRouteImport.update({
    id: '/matrices/create',
    path: '/matrices/create',
    getParentRoute: () => rootRouteImport,
} as any)
const CoursesWebDevelopmentRoute = CoursesWebDevelopmentRouteImport.update({
    id: '/courses/web-development',
    path: '/courses/web-development',
    getParentRoute: () => rootRouteImport,
} as any)
const CoursesMobileDevelopmentRoute = CoursesMobileDevelopmentRouteImport.update({
    id: '/courses/mobile-development',
    path: '/courses/mobile-development',
    getParentRoute: () => rootRouteImport,
} as any)
const CoursesDataScienceRoute = CoursesDataScienceRouteImport.update({
    id: '/courses/data-science',
    path: '/courses/data-science',
    getParentRoute: () => rootRouteImport,
} as any)
const CoursesBackendDevelopmentRoute = CoursesBackendDevelopmentRouteImport.update({
    id: '/courses/backend-development',
    path: '/courses/backend-development',
    getParentRoute: () => rootRouteImport,
} as any)
const CoursesIdRoute = CoursesIdRouteImport.update({
    id: '/courses/$id',
    path: '/courses/$id',
    getParentRoute: () => rootRouteImport,
} as any)
const TemplatesSlidevIndexRoute = TemplatesSlidevIndexRouteImport.update({
    id: '/templates/slidev/',
    path: '/templates/slidev/',
    getParentRoute: () => rootRouteImport,
} as any)
const TemplatesSlidevCreateRoute = TemplatesSlidevCreateRouteImport.update({
    id: '/templates/slidev/create',
    path: '/templates/slidev/create',
    getParentRoute: () => rootRouteImport,
} as any)
const PresentationsIdViewRoute = PresentationsIdViewRouteImport.update({
    id: '/view',
    path: '/view',
    getParentRoute: () => PresentationsIdRoute,
} as any)
const PresentationsIdPresenterRoute = PresentationsIdPresenterRouteImport.update({
    id: '/presenter',
    path: '/presenter',
    getParentRoute: () => PresentationsIdRoute,
} as any)
const PresentationsIdOverviewRoute = PresentationsIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => PresentationsIdRoute,
} as any)
const MatricesIdGenerateRoute = MatricesIdGenerateRouteImport.update({
    id: '/matrices/$id/generate',
    path: '/matrices/$id/generate',
    getParentRoute: () => rootRouteImport,
} as any)
const MatricesIdEditRoute = MatricesIdEditRouteImport.update({
    id: '/matrices/$id/edit',
    path: '/matrices/$id/edit',
    getParentRoute: () => rootRouteImport,
} as any)
const TemplatesSlidevIdEditRoute = TemplatesSlidevIdEditRouteImport.update({
    id: '/templates/slidev/$id/edit',
    path: '/templates/slidev/$id/edit',
    getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
    '/': typeof IndexRoute
    '/about': typeof AboutRoute
    '/chat': typeof ChatRoute
    '/consultation': typeof ConsultationRoute
    '/contact': typeof ContactRoute
    '/corporate-training': typeof CorporateTrainingRoute
    '/custom-template': typeof CustomTemplateRoute
    '/demo': typeof DemoRoute
    '/forgot-password': typeof ForgotPasswordRoute
    '/mentorship': typeof MentorshipRoute
    '/offline-course': typeof OfflineCourseRoute
    '/privacy': typeof PrivacyRoute
    '/reset-password': typeof ResetPasswordRoute
    '/signin': typeof SigninRoute
    '/signup': typeof SignupRoute
    '/terms': typeof TermsRoute
    '/upload': typeof UploadRoute
    '/user-profile': typeof UserProfileRoute
    '/web-design': typeof WebDesignRoute
    '/courses/$id': typeof CoursesIdRoute
    '/courses/backend-development': typeof CoursesBackendDevelopmentRoute
    '/courses/data-science': typeof CoursesDataScienceRoute
    '/courses/mobile-development': typeof CoursesMobileDevelopmentRoute
    '/courses/web-development': typeof CoursesWebDevelopmentRoute
    '/matrices/create': typeof MatricesCreateRoute
    '/matrices/import': typeof MatricesImportRoute
    '/news/$id': typeof NewsIdRoute
    '/presentations/$id': typeof PresentationsIdRouteWithChildren
    '/templates/$id': typeof TemplatesIdRoute
    '/templates/dashboard': typeof TemplatesDashboardRoute
    '/templates/template-preview': typeof TemplatesTemplatePreviewRoute
    '/courses': typeof CoursesIndexRoute
    '/matrices': typeof MatricesIndexRoute
    '/news': typeof NewsIndexRoute
    '/presentations': typeof PresentationsIndexRoute
    '/templates': typeof TemplatesIndexRoute
    '/matrices/$id/edit': typeof MatricesIdEditRoute
    '/matrices/$id/generate': typeof MatricesIdGenerateRoute
    '/presentations/$id/overview': typeof PresentationsIdOverviewRoute
    '/presentations/$id/presenter': typeof PresentationsIdPresenterRoute
    '/presentations/$id/view': typeof PresentationsIdViewRoute
    '/templates/slidev/create': typeof TemplatesSlidevCreateRoute
    '/templates/slidev': typeof TemplatesSlidevIndexRoute
    '/templates/slidev/$id/edit': typeof TemplatesSlidevIdEditRoute
}
export interface FileRoutesByTo {
    '/': typeof IndexRoute
    '/about': typeof AboutRoute
    '/chat': typeof ChatRoute
    '/consultation': typeof ConsultationRoute
    '/contact': typeof ContactRoute
    '/corporate-training': typeof CorporateTrainingRoute
    '/custom-template': typeof CustomTemplateRoute
    '/demo': typeof DemoRoute
    '/forgot-password': typeof ForgotPasswordRoute
    '/mentorship': typeof MentorshipRoute
    '/offline-course': typeof OfflineCourseRoute
    '/privacy': typeof PrivacyRoute
    '/reset-password': typeof ResetPasswordRoute
    '/signin': typeof SigninRoute
    '/signup': typeof SignupRoute
    '/terms': typeof TermsRoute
    '/upload': typeof UploadRoute
    '/user-profile': typeof UserProfileRoute
    '/web-design': typeof WebDesignRoute
    '/courses/$id': typeof CoursesIdRoute
    '/courses/backend-development': typeof CoursesBackendDevelopmentRoute
    '/courses/data-science': typeof CoursesDataScienceRoute
    '/courses/mobile-development': typeof CoursesMobileDevelopmentRoute
    '/courses/web-development': typeof CoursesWebDevelopmentRoute
    '/matrices/create': typeof MatricesCreateRoute
    '/matrices/import': typeof MatricesImportRoute
    '/news/$id': typeof NewsIdRoute
    '/presentations/$id': typeof PresentationsIdRouteWithChildren
    '/templates/$id': typeof TemplatesIdRoute
    '/templates/dashboard': typeof TemplatesDashboardRoute
    '/templates/template-preview': typeof TemplatesTemplatePreviewRoute
    '/courses': typeof CoursesIndexRoute
    '/matrices': typeof MatricesIndexRoute
    '/news': typeof NewsIndexRoute
    '/presentations': typeof PresentationsIndexRoute
    '/templates': typeof TemplatesIndexRoute
    '/matrices/$id/edit': typeof MatricesIdEditRoute
    '/matrices/$id/generate': typeof MatricesIdGenerateRoute
    '/presentations/$id/overview': typeof PresentationsIdOverviewRoute
    '/presentations/$id/presenter': typeof PresentationsIdPresenterRoute
    '/presentations/$id/view': typeof PresentationsIdViewRoute
    '/templates/slidev/create': typeof TemplatesSlidevCreateRoute
    '/templates/slidev': typeof TemplatesSlidevIndexRoute
    '/templates/slidev/$id/edit': typeof TemplatesSlidevIdEditRoute
}
export interface FileRoutesById {
    __root__: typeof rootRouteImport
    '/': typeof IndexRoute
    '/about': typeof AboutRoute
    '/chat': typeof ChatRoute
    '/consultation': typeof ConsultationRoute
    '/contact': typeof ContactRoute
    '/corporate-training': typeof CorporateTrainingRoute
    '/custom-template': typeof CustomTemplateRoute
    '/demo': typeof DemoRoute
    '/forgot-password': typeof ForgotPasswordRoute
    '/mentorship': typeof MentorshipRoute
    '/offline-course': typeof OfflineCourseRoute
    '/privacy': typeof PrivacyRoute
    '/reset-password': typeof ResetPasswordRoute
    '/signin': typeof SigninRoute
    '/signup': typeof SignupRoute
    '/terms': typeof TermsRoute
    '/upload': typeof UploadRoute
    '/user-profile': typeof UserProfileRoute
    '/web-design': typeof WebDesignRoute
    '/courses/$id': typeof CoursesIdRoute
    '/courses/backend-development': typeof CoursesBackendDevelopmentRoute
    '/courses/data-science': typeof CoursesDataScienceRoute
    '/courses/mobile-development': typeof CoursesMobileDevelopmentRoute
    '/courses/web-development': typeof CoursesWebDevelopmentRoute
    '/matrices/create': typeof MatricesCreateRoute
    '/matrices/import': typeof MatricesImportRoute
    '/news/$id': typeof NewsIdRoute
    '/presentations/$id': typeof PresentationsIdRouteWithChildren
    '/templates/$id': typeof TemplatesIdRoute
    '/templates/dashboard': typeof TemplatesDashboardRoute
    '/templates/template-preview': typeof TemplatesTemplatePreviewRoute
    '/courses/': typeof CoursesIndexRoute
    '/matrices/': typeof MatricesIndexRoute
    '/news/': typeof NewsIndexRoute
    '/presentations/': typeof PresentationsIndexRoute
    '/templates/': typeof TemplatesIndexRoute
    '/matrices/$id/edit': typeof MatricesIdEditRoute
    '/matrices/$id/generate': typeof MatricesIdGenerateRoute
    '/presentations/$id/overview': typeof PresentationsIdOverviewRoute
    '/presentations/$id/presenter': typeof PresentationsIdPresenterRoute
    '/presentations/$id/view': typeof PresentationsIdViewRoute
    '/templates/slidev/create': typeof TemplatesSlidevCreateRoute
    '/templates/slidev/': typeof TemplatesSlidevIndexRoute
    '/templates/slidev/$id/edit': typeof TemplatesSlidevIdEditRoute
}
export interface FileRouteTypes {
    fileRoutesByFullPath: FileRoutesByFullPath
    fullPaths:
        | '/'
        | '/about'
        | '/chat'
        | '/consultation'
        | '/contact'
        | '/corporate-training'
        | '/custom-template'
        | '/demo'
        | '/forgot-password'
        | '/mentorship'
        | '/offline-course'
        | '/privacy'
        | '/reset-password'
        | '/signin'
        | '/signup'
        | '/terms'
        | '/upload'
        | '/user-profile'
        | '/web-design'
        | '/courses/$id'
        | '/courses/backend-development'
        | '/courses/data-science'
        | '/courses/mobile-development'
        | '/courses/web-development'
        | '/matrices/create'
        | '/matrices/import'
        | '/news/$id'
        | '/presentations/$id'
        | '/templates/$id'
        | '/templates/dashboard'
        | '/templates/template-preview'
        | '/courses'
        | '/matrices'
        | '/news'
        | '/presentations'
        | '/templates'
        | '/matrices/$id/edit'
        | '/matrices/$id/generate'
        | '/presentations/$id/overview'
        | '/presentations/$id/presenter'
        | '/presentations/$id/view'
        | '/templates/slidev/create'
        | '/templates/slidev'
        | '/templates/slidev/$id/edit'
    fileRoutesByTo: FileRoutesByTo
    to:
        | '/'
        | '/about'
        | '/chat'
        | '/consultation'
        | '/contact'
        | '/corporate-training'
        | '/custom-template'
        | '/demo'
        | '/forgot-password'
        | '/mentorship'
        | '/offline-course'
        | '/privacy'
        | '/reset-password'
        | '/signin'
        | '/signup'
        | '/terms'
        | '/upload'
        | '/user-profile'
        | '/web-design'
        | '/courses/$id'
        | '/courses/backend-development'
        | '/courses/data-science'
        | '/courses/mobile-development'
        | '/courses/web-development'
        | '/matrices/create'
        | '/matrices/import'
        | '/news/$id'
        | '/presentations/$id'
        | '/templates/$id'
        | '/templates/dashboard'
        | '/templates/template-preview'
        | '/courses'
        | '/matrices'
        | '/news'
        | '/presentations'
        | '/templates'
        | '/matrices/$id/edit'
        | '/matrices/$id/generate'
        | '/presentations/$id/overview'
        | '/presentations/$id/presenter'
        | '/presentations/$id/view'
        | '/templates/slidev/create'
        | '/templates/slidev'
        | '/templates/slidev/$id/edit'
    id:
        | '__root__'
        | '/'
        | '/about'
        | '/chat'
        | '/consultation'
        | '/contact'
        | '/corporate-training'
        | '/custom-template'
        | '/demo'
        | '/forgot-password'
        | '/mentorship'
        | '/offline-course'
        | '/privacy'
        | '/reset-password'
        | '/signin'
        | '/signup'
        | '/terms'
        | '/upload'
        | '/user-profile'
        | '/web-design'
        | '/courses/$id'
        | '/courses/backend-development'
        | '/courses/data-science'
        | '/courses/mobile-development'
        | '/courses/web-development'
        | '/matrices/create'
        | '/matrices/import'
        | '/news/$id'
        | '/presentations/$id'
        | '/templates/$id'
        | '/templates/dashboard'
        | '/templates/template-preview'
        | '/courses/'
        | '/matrices/'
        | '/news/'
        | '/presentations/'
        | '/templates/'
        | '/matrices/$id/edit'
        | '/matrices/$id/generate'
        | '/presentations/$id/overview'
        | '/presentations/$id/presenter'
        | '/presentations/$id/view'
        | '/templates/slidev/create'
        | '/templates/slidev/'
        | '/templates/slidev/$id/edit'
    fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
    IndexRoute: typeof IndexRoute
    AboutRoute: typeof AboutRoute
    ChatRoute: typeof ChatRoute
    ConsultationRoute: typeof ConsultationRoute
    ContactRoute: typeof ContactRoute
    CorporateTrainingRoute: typeof CorporateTrainingRoute
    CustomTemplateRoute: typeof CustomTemplateRoute
    DemoRoute: typeof DemoRoute
    ForgotPasswordRoute: typeof ForgotPasswordRoute
    MentorshipRoute: typeof MentorshipRoute
    OfflineCourseRoute: typeof OfflineCourseRoute
    PrivacyRoute: typeof PrivacyRoute
    ResetPasswordRoute: typeof ResetPasswordRoute
    SigninRoute: typeof SigninRoute
    SignupRoute: typeof SignupRoute
    TermsRoute: typeof TermsRoute
    UploadRoute: typeof UploadRoute
    UserProfileRoute: typeof UserProfileRoute
    WebDesignRoute: typeof WebDesignRoute
    CoursesIdRoute: typeof CoursesIdRoute
    CoursesBackendDevelopmentRoute: typeof CoursesBackendDevelopmentRoute
    CoursesDataScienceRoute: typeof CoursesDataScienceRoute
    CoursesMobileDevelopmentRoute: typeof CoursesMobileDevelopmentRoute
    CoursesWebDevelopmentRoute: typeof CoursesWebDevelopmentRoute
    MatricesCreateRoute: typeof MatricesCreateRoute
    MatricesImportRoute: typeof MatricesImportRoute
    NewsIdRoute: typeof NewsIdRoute
    PresentationsIdRoute: typeof PresentationsIdRouteWithChildren
    TemplatesIdRoute: typeof TemplatesIdRoute
    TemplatesDashboardRoute: typeof TemplatesDashboardRoute
    TemplatesTemplatePreviewRoute: typeof TemplatesTemplatePreviewRoute
    CoursesIndexRoute: typeof CoursesIndexRoute
    MatricesIndexRoute: typeof MatricesIndexRoute
    NewsIndexRoute: typeof NewsIndexRoute
    PresentationsIndexRoute: typeof PresentationsIndexRoute
    TemplatesIndexRoute: typeof TemplatesIndexRoute
    MatricesIdEditRoute: typeof MatricesIdEditRoute
    MatricesIdGenerateRoute: typeof MatricesIdGenerateRoute
    TemplatesSlidevCreateRoute: typeof TemplatesSlidevCreateRoute
    TemplatesSlidevIndexRoute: typeof TemplatesSlidevIndexRoute
    TemplatesSlidevIdEditRoute: typeof TemplatesSlidevIdEditRoute
}

declare module '@tanstack/react-router' {
    interface FileRoutesByPath {
        '/web-design': {
            id: '/web-design'
            path: '/web-design'
            fullPath: '/web-design'
            preLoaderRoute: typeof WebDesignRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/user-profile': {
            id: '/user-profile'
            path: '/user-profile'
            fullPath: '/user-profile'
            preLoaderRoute: typeof UserProfileRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/upload': {
            id: '/upload'
            path: '/upload'
            fullPath: '/upload'
            preLoaderRoute: typeof UploadRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/terms': {
            id: '/terms'
            path: '/terms'
            fullPath: '/terms'
            preLoaderRoute: typeof TermsRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/signup': {
            id: '/signup'
            path: '/signup'
            fullPath: '/signup'
            preLoaderRoute: typeof SignupRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/signin': {
            id: '/signin'
            path: '/signin'
            fullPath: '/signin'
            preLoaderRoute: typeof SigninRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/reset-password': {
            id: '/reset-password'
            path: '/reset-password'
            fullPath: '/reset-password'
            preLoaderRoute: typeof ResetPasswordRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/privacy': {
            id: '/privacy'
            path: '/privacy'
            fullPath: '/privacy'
            preLoaderRoute: typeof PrivacyRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/offline-course': {
            id: '/offline-course'
            path: '/offline-course'
            fullPath: '/offline-course'
            preLoaderRoute: typeof OfflineCourseRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/mentorship': {
            id: '/mentorship'
            path: '/mentorship'
            fullPath: '/mentorship'
            preLoaderRoute: typeof MentorshipRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/forgot-password': {
            id: '/forgot-password'
            path: '/forgot-password'
            fullPath: '/forgot-password'
            preLoaderRoute: typeof ForgotPasswordRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/demo': {
            id: '/demo'
            path: '/demo'
            fullPath: '/demo'
            preLoaderRoute: typeof DemoRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/custom-template': {
            id: '/custom-template'
            path: '/custom-template'
            fullPath: '/custom-template'
            preLoaderRoute: typeof CustomTemplateRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/corporate-training': {
            id: '/corporate-training'
            path: '/corporate-training'
            fullPath: '/corporate-training'
            preLoaderRoute: typeof CorporateTrainingRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/contact': {
            id: '/contact'
            path: '/contact'
            fullPath: '/contact'
            preLoaderRoute: typeof ContactRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/consultation': {
            id: '/consultation'
            path: '/consultation'
            fullPath: '/consultation'
            preLoaderRoute: typeof ConsultationRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/chat': {
            id: '/chat'
            path: '/chat'
            fullPath: '/chat'
            preLoaderRoute: typeof ChatRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/about': {
            id: '/about'
            path: '/about'
            fullPath: '/about'
            preLoaderRoute: typeof AboutRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/': {
            id: '/'
            path: '/'
            fullPath: '/'
            preLoaderRoute: typeof IndexRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/templates/': {
            id: '/templates/'
            path: '/templates'
            fullPath: '/templates'
            preLoaderRoute: typeof TemplatesIndexRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/news/': {
            id: '/news/'
            path: '/news'
            fullPath: '/news'
            preLoaderRoute: typeof NewsIndexRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/presentations/': {
            id: '/presentations/'
            path: '/presentations'
            fullPath: '/presentations'
            preLoaderRoute: typeof PresentationsIndexRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/matrices/': {
            id: '/matrices/'
            path: '/matrices'
            fullPath: '/matrices'
            preLoaderRoute: typeof MatricesIndexRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/courses/': {
            id: '/courses/'
            path: '/courses'
            fullPath: '/courses'
            preLoaderRoute: typeof CoursesIndexRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/templates/template-preview': {
            id: '/templates/template-preview'
            path: '/templates/template-preview'
            fullPath: '/templates/template-preview'
            preLoaderRoute: typeof TemplatesTemplatePreviewRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/templates/dashboard': {
            id: '/templates/dashboard'
            path: '/templates/dashboard'
            fullPath: '/templates/dashboard'
            preLoaderRoute: typeof TemplatesDashboardRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/templates/$id': {
            id: '/templates/$id'
            path: '/templates/$id'
            fullPath: '/templates/$id'
            preLoaderRoute: typeof TemplatesIdRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/presentations/$id': {
            id: '/presentations/$id'
            path: '/presentations/$id'
            fullPath: '/presentations/$id'
            preLoaderRoute: typeof PresentationsIdRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/news/$id': {
            id: '/news/$id'
            path: '/news/$id'
            fullPath: '/news/$id'
            preLoaderRoute: typeof NewsIdRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/matrices/import': {
            id: '/matrices/import'
            path: '/matrices/import'
            fullPath: '/matrices/import'
            preLoaderRoute: typeof MatricesImportRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/matrices/create': {
            id: '/matrices/create'
            path: '/matrices/create'
            fullPath: '/matrices/create'
            preLoaderRoute: typeof MatricesCreateRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/courses/web-development': {
            id: '/courses/web-development'
            path: '/courses/web-development'
            fullPath: '/courses/web-development'
            preLoaderRoute: typeof CoursesWebDevelopmentRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/courses/mobile-development': {
            id: '/courses/mobile-development'
            path: '/courses/mobile-development'
            fullPath: '/courses/mobile-development'
            preLoaderRoute: typeof CoursesMobileDevelopmentRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/courses/data-science': {
            id: '/courses/data-science'
            path: '/courses/data-science'
            fullPath: '/courses/data-science'
            preLoaderRoute: typeof CoursesDataScienceRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/courses/backend-development': {
            id: '/courses/backend-development'
            path: '/courses/backend-development'
            fullPath: '/courses/backend-development'
            preLoaderRoute: typeof CoursesBackendDevelopmentRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/courses/$id': {
            id: '/courses/$id'
            path: '/courses/$id'
            fullPath: '/courses/$id'
            preLoaderRoute: typeof CoursesIdRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/templates/slidev/': {
            id: '/templates/slidev/'
            path: '/templates/slidev'
            fullPath: '/templates/slidev'
            preLoaderRoute: typeof TemplatesSlidevIndexRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/templates/slidev/create': {
            id: '/templates/slidev/create'
            path: '/templates/slidev/create'
            fullPath: '/templates/slidev/create'
            preLoaderRoute: typeof TemplatesSlidevCreateRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/matrices/$id/generate': {
            id: '/matrices/$id/generate'
            path: '/matrices/$id/generate'
            fullPath: '/matrices/$id/generate'
            preLoaderRoute: typeof MatricesIdGenerateRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/matrices/$id/edit': {
            id: '/matrices/$id/edit'
            path: '/matrices/$id/edit'
            fullPath: '/matrices/$id/edit'
            preLoaderRoute: typeof MatricesIdEditRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/templates/slidev/$id/edit': {
            id: '/templates/slidev/$id/edit'
            path: '/templates/slidev/$id/edit'
            fullPath: '/templates/slidev/$id/edit'
            preLoaderRoute: typeof TemplatesSlidevIdEditRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/presentations/$id/view': {
            id: '/presentations/$id/view'
            path: '/view'
            fullPath: '/presentations/$id/view'
            preLoaderRoute: typeof PresentationsIdViewRouteImport
            parentRoute: typeof PresentationsIdRoute
        }
        '/presentations/$id/presenter': {
            id: '/presentations/$id/presenter'
            path: '/presenter'
            fullPath: '/presentations/$id/presenter'
            preLoaderRoute: typeof PresentationsIdPresenterRouteImport
            parentRoute: typeof PresentationsIdRoute
        }
        '/presentations/$id/overview': {
            id: '/presentations/$id/overview'
            path: '/overview'
            fullPath: '/presentations/$id/overview'
            preLoaderRoute: typeof PresentationsIdOverviewRouteImport
            parentRoute: typeof PresentationsIdRoute
        }
    }
}

interface PresentationsIdRouteChildren {
    PresentationsIdOverviewRoute: typeof PresentationsIdOverviewRoute
    PresentationsIdPresenterRoute: typeof PresentationsIdPresenterRoute
    PresentationsIdViewRoute: typeof PresentationsIdViewRoute
}

const PresentationsIdRouteChildren: PresentationsIdRouteChildren = {
    PresentationsIdOverviewRoute: PresentationsIdOverviewRoute,
    PresentationsIdPresenterRoute: PresentationsIdPresenterRoute,
    PresentationsIdViewRoute: PresentationsIdViewRoute,
}

const PresentationsIdRouteWithChildren = PresentationsIdRoute._addFileChildren(PresentationsIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
    IndexRoute: IndexRoute,
    AboutRoute: AboutRoute,
    ChatRoute: ChatRoute,
    ConsultationRoute: ConsultationRoute,
    ContactRoute: ContactRoute,
    CorporateTrainingRoute: CorporateTrainingRoute,
    CustomTemplateRoute: CustomTemplateRoute,
    DemoRoute: DemoRoute,
    ForgotPasswordRoute: ForgotPasswordRoute,
    MentorshipRoute: MentorshipRoute,
    OfflineCourseRoute: OfflineCourseRoute,
    PrivacyRoute: PrivacyRoute,
    ResetPasswordRoute: ResetPasswordRoute,
    SigninRoute: SigninRoute,
    SignupRoute: SignupRoute,
    TermsRoute: TermsRoute,
    UploadRoute: UploadRoute,
    UserProfileRoute: UserProfileRoute,
    WebDesignRoute: WebDesignRoute,
    CoursesIdRoute: CoursesIdRoute,
    CoursesBackendDevelopmentRoute: CoursesBackendDevelopmentRoute,
    CoursesDataScienceRoute: CoursesDataScienceRoute,
    CoursesMobileDevelopmentRoute: CoursesMobileDevelopmentRoute,
    CoursesWebDevelopmentRoute: CoursesWebDevelopmentRoute,
    MatricesCreateRoute: MatricesCreateRoute,
    MatricesImportRoute: MatricesImportRoute,
    NewsIdRoute: NewsIdRoute,
    PresentationsIdRoute: PresentationsIdRouteWithChildren,
    TemplatesIdRoute: TemplatesIdRoute,
    TemplatesDashboardRoute: TemplatesDashboardRoute,
    TemplatesTemplatePreviewRoute: TemplatesTemplatePreviewRoute,
    CoursesIndexRoute: CoursesIndexRoute,
    MatricesIndexRoute: MatricesIndexRoute,
    NewsIndexRoute: NewsIndexRoute,
    PresentationsIndexRoute: PresentationsIndexRoute,
    TemplatesIndexRoute: TemplatesIndexRoute,
    MatricesIdEditRoute: MatricesIdEditRoute,
    MatricesIdGenerateRoute: MatricesIdGenerateRoute,
    TemplatesSlidevCreateRoute: TemplatesSlidevCreateRoute,
    TemplatesSlidevIndexRoute: TemplatesSlidevIndexRoute,
    TemplatesSlidevIdEditRoute: TemplatesSlidevIdEditRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()
